version: "3.8"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: gastro_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: